import sharp from 'sharp'
import { BackgroundResources } from './resources/background.mjs'
import { MiscResources } from './resources/misc.mjs'

export const generate = async (
    background: BackgroundResources,
    misc: MiscResources,
    packageName: string,
    packageVersion: string
) => {
    const name = `llsif-${background.name}`
    console.log('Generating', name, 'resources...')

    const info = getInfo(background.name, packageName, packageVersion)
    const image = getImage(background.image)
    const thumbnail = getThumbnail(background.thumbnail)

    return {
        name,

        info,
        data: misc.data,
        configuration: misc.configuration,
        image,
        thumbnail,
    }
}

const getInfo = (name: string, packageName: string, packageVersion: string) => ({
    version: 2,
    title: { ja: name.toUpperCase() },
    subtitle: {
        en: 'Love Live! School idol festival',
        ja: 'ラブライブ！スクールアイドルフェスティバル',
        ko: '러브라이브 스쿨 아이돌 페스티벌',
        zhs: 'Love Live! 学园偶像祭',
        zht: 'Love Live! 學園偶像祭',
    },
    author: {
        en: 'Burrito',
    },
    description: {
        en: [
            'Generated by:',
            packageName,
            '',
            'Version:',
            packageVersion,
            '',
            'GitHub Repository:',
            'https://github.com/NonSpicyBurrito/sonolus-llsif-background-generator',
        ].join('\n'),
    },
})

const getImage = (image: Buffer) => sharp(image).png({ compressionLevel: 9 })

const getThumbnail = (thumbnail: Buffer) =>
    sharp(thumbnail)
        .resize(554, 256, { fit: 'fill' })
        .extract({ left: 149, top: 0, width: 256, height: 256 })
        .png({ compressionLevel: 9 })
